
##################################################
###   Visit https://github.com/tinybirdco/ci   ###
###   for more details or custom CI/CD         ###
##################################################

name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize, closed]
    paths:
      - 'tinybird/**'

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
    ci: # ci using branches from workspace 'analytics_events'
      uses: ./template_ci_using_docker.yml
      with:
        data_project_dir: tinybird
      secrets:
        tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN }}  # set the Workspace admin token in GitHub secrets
        tb_host: https://ui.us-east.tinybird.co
